### ISSUE TITLE
Content Rating

### ISSUE THREAD

**Issue by romanzipp** [Streamfinity/Extension#2]
[**API endpoint docs**](https://development-backend.streamfinity.tv/nova/api-docs#tag/Content-Rating)

```[tasklist]
### Tasks
- [x] Display content rating (animated red badge if TOS)
- [x] Allow submission of content rating
- [x] Submit content rating with timestamps
- [ ] Add prompt if redirect with URL hash "#content-rating-prompt" (from public suggestions page)
- [ ] Only allow submitting segment, if watched for x seconds
- [ ] Allow rating whole video as "safe"
```

## Parent issue

https://github.com/Streamfinity/Backend/issues/62
