### ISSUE TITLE
Add Community Notes

### ISSUE THREAD

**Issue by romanzipp** [Streamfinity/Extension#31]
### Frontend: https://github.com/Streamfinity/Frontend/issues/70

---

```[tasklist]
### Tasks
- [x] Display "best" community note
- [x] Include link to vote on community note
- [x] Allow adding community notes via Ext
- [ ] Allow clickable timestamps
```
