### ISSUE TITLE
Add more premium CTAs

### ISSUE THREAD

**Issue by romanzipp** [Streamfinity/Extension#48]
```[tasklist]
### Tasks
- [x] Creator: Blur analytics if existing
- [x] Creator: Only show that *some* streamer/creator has reacted to a video
- [x] Community: Dont show which of their followed streamers reacted to video
```
