### ISSUE TITLE
Review Status

### ISSUE THREAD

**Issue by romanzipp** [Streamfinity/Extension#58]
```[tasklist]
### Tasks
- [x] Google Web Store: accepted
- [x] Microsoft Edge Store: pending...
- [x] Firefox AMO: accepted
```
