### ISSUE TITLE
Reaction Policy

### ISSUE THREAD

**Issue by romanzipp** [Streamfinity/Extension#9]
```[tasklist]
### Tasks
- [x] Show reaction policy status beneath video
- [x] Flash if outside of condition boundaries
- [x] Show comment
- [x] Add link or creators to edit/create Policy if on own videos
```
